spring:
  profiles:
    active: ${PROFILE}
  main:
    allow-bean-definition-overriding: true

jwt:
    secret: randomTestValueItisNotUsedInProdEnv
    expiration: 1800000
    # 30 minutes
    refresh:
        expiration: 604800000
    # 7 days